# Generated by Django 6.0.1 on 2026-01-15 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable system identifier, e.g. FOOD, TRANSPORT', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable category name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base Category',
                'verbose_name_plural': 'Base Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_categories', to='categories.basecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
