# Generated by Django 6.0.1 on 2026-01-15 17:42

from django.db import migrations

def seed_base_categories(apps, schema_editor):
    BaseCategory = apps.get_model("categories", "BaseCategory")

    categories = [
        ("FOOD", "Food & Dining"),
        ("TRANSPORT", "Transport"),
        ("GROCERIES", "Groceries"),
        ("BILLS", "Bills & Utilities"),
        ("RENT", "Rent"),
        ("ENTERTAINMENT", "Entertainment"),
        ("SHOPPING", "Shopping"),
        ("HEALTH", "Health & Medical"),
        ("EDUCATION", "Education"),
        ("TRAVEL", "Travel"),
        ("MISC", "Miscellaneous"),
    ]

    for code, name in categories:
        BaseCategory.objects.get_or_create(
            code=code,
            defaults={"name": name}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_base_categories),
    ]
